# -*- coding: utf-8 -*-
"""yolov5s (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k83iMrx76b8gH2pf1NFAP2t-vIyVt-BW
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5 /content/drive/MyDrive/yolov5s_models/yolov5s
# %cd /content/drive/MyDrive/yolov5s_models/yolov5s

# Commented out IPython magic to ensure Python compatibility.
# %pip install -r requirements.txt

!mkdir -p /content/drive/MyDrive/yolov5s_models/training_output/yolov5s_dental
!mkdir -p /content/drive/MyDrive/yolov5s_models/val_output
!mkdir -p /content/drive/MyDrive/yolov5s_models/detect_output

yaml_path = "/content/drive/MyDrive/yolov5s_models/dental_dataset.yaml"

yaml_content = """
train: /content/drive/MyDrive/enhanced/train
val: /content/drive/MyDrive/enhanced/valid
test: /content/drive/MyDrive/enhanced/test

nc: 6
names: ['Fillings', 'Implant', 'Impacted Tooth', 'Cavity', 'Fractured teeth', 'Infection']
"""

with open(yaml_path, "w") as f:
    f.write(yaml_content.strip())

!rm /content/drive/MyDrive/enhanced/train/.cache
!rm /content/drive/MyDrive/enhanced/valid/.cache
!rm /content/drive/MyDrive/enhanced/test/.cache

!python train.py \
    --img 640 \
    --batch 16 \
    --epochs 50 \
    --data /content/drive/MyDrive/yolov5s_models/dental_dataset.yaml \
    --weights yolov5s.pt \
    --project /content/drive/MyDrive/yolov5s_models/training_output \
    --name yolov5s_dental \
    --exist-ok

# Run detection
!python detect.py \
    --weights /content/drive/MyDrive/yolov5s_models/training_output/yolov5s_dental/weights/best.pt \
    --source /content/drive/MyDrive/enhanced/test \
    --img 640 \
    --conf 0.25 \
    --iou 0.45 \
    --save-txt \
    --save-conf \
    --project /content/drive/MyDrive/yolov5s_models/detect_output \
    --name yolov5s_results \
    --exist-ok

# Run validation
!python val.py \
    --weights /content/drive/MyDrive/yolov5s_models/training_output/yolov5s_dental/weights/best.pt \
    --data /content/drive/MyDrive/yolov5s_models/dental_dataset.yaml \
    --img 640 \
    --task test \
    --save-txt \
    --save-conf \
    --project /content/drive/MyDrive/yolov5s_models/val_output \
    --name yolov5s_eval

!ls /content

!git clone https://github.com/ultralytics/yolov5.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolov5

!git clone https://github.com/ultralytics/yolov5.git /content/drive/MyDrive/yolov5

!ls runs/val/

!python3 val.py --weights /content/drive/MyDrive/yolov5s_models/training_output/yolov5s_dental/weights/best.pt \
                --data /content/drive/MyDrive/yolov5s_models/dental_dataset.yaml \
                --task test \
                --img 640 \
                --project /content/runs/ \
                --name val_test_results