# -*- coding: utf-8 -*-
"""yolov5 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-KiXggXzgCqWsV7zOwUrMda75W08oXZ
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5.git /content/drive/MyDrive/yolov5_models/yolov5s
# %cd /content/drive/MyDrive/yolov5_models/yolov5s

!pip install -qr requirements.txt

!pip install thop

yaml_content = """
train: /content/drive/MyDrive/enhanced/train
val: /content/drive/MyDrive/enhanced/valid
test: /content/drive/MyDrive/enhanced/test

nc: 6
names: ['Fillings', 'Implant', 'Impacted Tooth', 'Cavity', 'Fractured teeth', 'Infection']
"""

yaml_path = "/content/drive/MyDrive/yolov5_models/dental_dataset.yaml"
with open(yaml_path, "w") as f:
    f.write(yaml_content)

!rm -f /content/drive/MyDrive/enhanced/train/.cache
!rm -f /content/drive/MyDrive/enhanced/valid/.cache
!rm -f /content/drive/MyDrive/enhanced/test/.cache

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolov5_models/yolov5s

!python train.py \
    --img 640 \
    --batch 16 \
    --epochs 50 \
    --data /content/drive/MyDrive/yolov5_models/dental_dataset.yaml \
    --weights yolov5s.pt \
    --name yolov5s_dental \
    --project /content/drive/MyDrive/yolov5_models/training_output

!python /content/drive/MyDrive/yolov5_models/yolov5s/detect.py \
  --weights /content/drive/MyDrive/yolov5_models/training_output/yolov5s_dental/weights/best.pt \
  --source /content/drive/MyDrive/enhanced/test \
  --data /content/drive/MyDrive/yolov5_models/dental_dataset.yaml \
  --img 640 \
  --conf 0.25 \
  --iou 0.45 \
  --save-txt \
  --save-conf \
  --project /content/drive/MyDrive/yolov5_models/detect_output \
  --name yolov5s_results

# Evaluation using val.py
!python /content/drive/MyDrive/yolov5_models/yolov5s/val.py \
    --weights /content/drive/MyDrive/yolov5_models/training_output/yolov5s_dental/weights/best.pt \
    --data /content/drive/MyDrive/yolov5_models/dental_dataset.yaml \
    --img 640 \
    --task test \
    --save-txt \
    --save-conf \
    --project /content/drive/MyDrive/yolov5_models/val_output \
    --name yolov5s_eval

