# -*- coding: utf-8 -*-
"""yolov8s (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QpDv3JmT1A6CeFzqm-13YWeDINfqsjQ5
"""

from google.colab import drive
drive.mount('/content/drive')

# Install YOLOv8
!pip install ultralytics

# Import and check version
from ultralytics import YOLO
import torch
print(torch.__version__)

# Commented out IPython magic to ensure Python compatibility.
# Clone YOLOv8 repository into a separate folder
!git clone https://github.com/ultralytics/ultralytics /content/drive/MyDrive/yolov8s_models/yolov8s

# Change directory to the cloned folder
# %cd /content/drive/MyDrive/yolov8s_models/yolov8s

yaml_path = "/content/drive/MyDrive/yolov8s_models/yolov8s/dental_dataset.yaml"

yaml_content = """
train: /content/drive/MyDrive/enhanced/train
val: /content/drive/MyDrive/enhanced/valid
test: /content/drive/MyDrive/enhanced/test

nc: 6
names: ['Fillings', 'Implant', 'Impacted Tooth', 'Cavity', 'Fractured teeth', 'Infection']
"""

with open(yaml_path, "w") as f:
    f.write(yaml_content.strip())

!rm /content/drive/MyDrive/enhanced/train/.cache
!rm /content/drive/MyDrive/enhanced/valid/.cache
!rm /content/drive/MyDrive/enhanced/test/.cache

!yolo task=detect mode=train \
    model=yolov8s.pt \
    data=/content/drive/MyDrive/yolov8s_models/yolov8s/dental_dataset.yaml \
    epochs=50 \
    imgsz=640 \
    batch=16 \
    name=yolov8s_dental \
    project=/content/drive/MyDrive/yolov8s_models/training_output \
    save_period=5

!yolo task=detect mode=predict \
    model=/content/drive/MyDrive/yolov8s_models/training_output/yolov8s_dental/weights/best.pt \
    source=/content/drive/MyDrive/enhanced/test \
    imgsz=640 \
    conf=0.25 \
    iou=0.45 \
    save_txt=True \
    save_conf=True \
    project=/content/drive/MyDrive/yolov8s_models/detect_output \
    name=yolov8s_results \
    line_thickness=3

!yolo task=detect mode=val \
    model=/content/drive/MyDrive/yolov8s_models/training_output/yolov8s_dental/weights/best.pt \
    data=/content/drive/MyDrive/yolov8s_models/yolov8s/dental_dataset.yaml \
    imgsz=640 \
    conf=0.25 \
    iou=0.45 \
    project=/content/drive/MyDrive/yolov8s_models/val_output \
    name=yolov8s_eval